# coordinates of the Husky's bounding box, (0,0) is at the center of the Husky
footprint: [[-0.52, -0.35],[-0.52, 0.35], [0.52, 0.35], [0.52, -0.35]]


inflation_radius: 0

# use transforms that are up to this many seconds old
transform_tolerance: 0.5

# observation sources to use on both maps
observation_sources: oak_point_cloud

# ZED observation source
oak_point_cloud:
  sensor_frame: oak-d-base-frame
  data_type: PointCloud2
  topic: /oak_depth/depth/points
  marking: true
  clearing: true
  obstacle_range: 2.5
  raytrace_range: 6.0
  max_obstacle_height: 0.8
  min_obstacle_height: 0.1
